---
kind: pipeline
type: docker
name: default

platform:
  os: linux
  arch: amd64

steps:
  - name: lint
    pull: always
    image: hadolint/hadolint:latest-debian
    commands:
      - hadolint Dockerfile
      - hadolint Dockerfile.netcore2
      - hadolint Dockerfile.mono
      - hadolint Dockerfile.mono-netcore2
    when:
      branch:
        - master
      event:
        - push
        - pull_request

  - name: docker-dotnet21
    pull: always
    image: plugins/docker:18
    settings:
      build_args:
        - DOTNET_VERSION=2.1-alpine3.9
        - SONAR_SCANNER_VERSION=5.0.4
      cache_from: zzdats/dotnet-sonarscanner
      dockerfile: Dockerfile.netcore2
      repo: zzdats/dotnet-sonarscanner
      tag:
        - 2.1
        - 2.1-5.0.4
    environment:
      DOCKER_PASSWORD:
        from_secret: docker_password
      DOCKER_USERNAME:
        from_secret: docker_username
    depends_on:
      - lint
    when:
      branch:
        - master
      event:
        - push

  - name: docker-dotnet31
    pull: always
    image: plugins/docker:18
    settings:
      build_args:
        - DOTNET_VERSION=3.1-alpine3.12
        - SONAR_SCANNER_VERSION=5.0.4
      cache_from: zzdats/dotnet-sonarscanner
      repo: zzdats/dotnet-sonarscanner
      tag:
        - 3.1
        - 3.1-5.0.4
    environment:
      DOCKER_PASSWORD:
        from_secret: docker_password
      DOCKER_USERNAME:
        from_secret: docker_username
    depends_on:
      - lint
    when:
      branch:
        - master
      event:
        - push

  - name: docker-dotnet5
    pull: always
    image: plugins/docker:18
    settings:
      build_args:
        - DOTNET_VERSION=5.0-alpine3.12
        - SONAR_SCANNER_VERSION=5.0.4
      cache_from: zzdats/dotnet-sonarscanner
      repo: zzdats/dotnet-sonarscanner
      tag:
        - latest
        - "5.0"
        - 5.0-5.0.4
    environment:
      DOCKER_PASSWORD:
        from_secret: docker_password
      DOCKER_USERNAME:
        from_secret: docker_username
    depends_on:
      - lint
    when:
      branch:
        - master
      event:
        - push

  - name: docker-dotnet21-mono
    pull: always
    image: plugins/docker:18
    settings:
      build_args:
        - DOTNET_VERSION=2.1-alpine3.9
        - SONAR_SCANNER_VERSION=5.0.4
      cache_from: zzdats/dotnet-sonarscanner
      dockerfile: Dockerfile.mono-netcore2
      repo: zzdats/dotnet-sonarscanner
      tag:
        - 2.1-mono
        - 2.1-5.0.4-mono
    environment:
      DOCKER_PASSWORD:
        from_secret: docker_password
      DOCKER_USERNAME:
        from_secret: docker_username
    depends_on:
      - lint
    when:
      branch:
        - master
      event:
        - push

  - name: docker-dotnet31-mono
    pull: always
    image: plugins/docker:18
    settings:
      build_args:
        - DOTNET_VERSION=3.1-alpine3.12
        - SONAR_SCANNER_VERSION=5.0.4
      cache_from: zzdats/dotnet-sonarscanner
      dockerfile: Dockerfile.mono
      repo: zzdats/dotnet-sonarscanner
      tag:
        - 3.1-mono
        - 3.1-5.0.4-mono
    environment:
      DOCKER_PASSWORD:
        from_secret: docker_password
      DOCKER_USERNAME:
        from_secret: docker_username
    depends_on:
      - lint
    when:
      branch:
        - master
      event:
        - push

  - name: docker-dotnet5-mono
    pull: always
    image: plugins/docker:18
    settings:
      build_args:
        - DOTNET_VERSION=5.0-alpine3.12
        - SONAR_SCANNER_VERSION=5.0.4
      cache_from: zzdats/dotnet-sonarscanner
      dockerfile: Dockerfile.mono
      repo: zzdats/dotnet-sonarscanner
      tag:
        - latest-mono
        - 5.0-mono
        - 5.0-5.0.4-mono
    environment:
      DOCKER_PASSWORD:
        from_secret: docker_password
      DOCKER_USERNAME:
        from_secret: docker_username
    depends_on:
      - lint
    when:
      branch:
        - master
      event:
        - push
