---
kind: pipeline
type: docker
name: default

platform:
  os: linux
  arch: amd64

steps:
  - name: lint
    pull: always
    image: hadolint/hadolint:latest-debian
    commands:
      - hadolint Dockerfile
      - hadolint Dockerfile.mono
    when:
      branch:
        - master
      event:
        - push
        - pull_request

  - name: docker-dotnet31
    pull: always
    image: plugins/docker:18
    settings:
      build_args:
        - DOTNET_VERSION=3.1-alpine3.14
        - SONAR_SCANNER_VERSION=5.4.1
      cache_from: zzdats/dotnet-sonarscanner
      repo: zzdats/dotnet-sonarscanner
      tag:
        - 3.1
        - 3.1-5.4.1
    environment:
      DOCKER_PASSWORD:
        from_secret: docker_password
      DOCKER_USERNAME:
        from_secret: docker_username
    depends_on:
      - lint
    when:
      branch:
        - master
      event:
        - push

  - name: docker-dotnet5
    pull: always
    image: plugins/docker:18
    settings:
      build_args:
        - DOTNET_VERSION=5.0-alpine3.14
        - SONAR_SCANNER_VERSION=5.4.1
      cache_from: zzdats/dotnet-sonarscanner
      repo: zzdats/dotnet-sonarscanner
      tag:
        - "5.0"
        - 5.0-5.4.1
    environment:
      DOCKER_PASSWORD:
        from_secret: docker_password
      DOCKER_USERNAME:
        from_secret: docker_username
    depends_on:
      - lint
    when:
      branch:
        - master
      event:
        - push

  - name: docker-dotnet6
    pull: always
    image: plugins/docker:18
    settings:
      build_args:
        - DOTNET_VERSION=6.0-alpine3.14
        - SONAR_SCANNER_VERSION=5.4.1
      cache_from: zzdats/dotnet-sonarscanner
      repo: zzdats/dotnet-sonarscanner
      tag:
        - latest
        - "6.0"
        - 6.0-5.4.1
    environment:
      DOCKER_PASSWORD:
        from_secret: docker_password
      DOCKER_USERNAME:
        from_secret: docker_username
    depends_on:
      - lint
    when:
      branch:
        - master
      event:
        - push

  - name: docker-dotnet31-mono
    pull: always
    image: plugins/docker:18
    settings:
      build_args:
        - DOTNET_VERSION=3.1-alpine3.14
        - SONAR_SCANNER_VERSION=5.4.1
      cache_from: zzdats/dotnet-sonarscanner
      dockerfile: Dockerfile.mono
      repo: zzdats/dotnet-sonarscanner
      tag:
        - 3.1-mono
        - 3.1-5.4.1-mono
    environment:
      DOCKER_PASSWORD:
        from_secret: docker_password
      DOCKER_USERNAME:
        from_secret: docker_username
    depends_on:
      - lint
    when:
      branch:
        - master
      event:
        - push

  - name: docker-dotnet5-mono
    pull: always
    image: plugins/docker:18
    settings:
      build_args:
        - DOTNET_VERSION=5.0-alpine3.14
        - SONAR_SCANNER_VERSION=5.4.1
      cache_from: zzdats/dotnet-sonarscanner
      dockerfile: Dockerfile.mono
      repo: zzdats/dotnet-sonarscanner
      tag:
        - 5.0-mono
        - 5.0-5.4.1-mono
    environment:
      DOCKER_PASSWORD:
        from_secret: docker_password
      DOCKER_USERNAME:
        from_secret: docker_username
    depends_on:
      - lint
    when:
      branch:
        - master
      event:
        - push

  - name: docker-dotnet6-mono
    pull: always
    image: plugins/docker:18
    settings:
      build_args:
        - DOTNET_VERSION=6.0-alpine3.14
        - SONAR_SCANNER_VERSION=5.4.1
      cache_from: zzdats/dotnet-sonarscanner
      dockerfile: Dockerfile.mono
      repo: zzdats/dotnet-sonarscanner
      tag:
        - latest-mono
        - 6.0-mono
        - 6.0-5.4.1-mono
    environment:
      DOCKER_PASSWORD:
        from_secret: docker_password
      DOCKER_USERNAME:
        from_secret: docker_username
    depends_on:
      - lint
    when:
      branch:
        - master
      event:
        - push
