---
kind: pipeline
type: docker
name: default

platform:
  os: linux
  arch: amd64

steps:
  - name: lint
    pull: always
    image: hadolint/hadolint:latest-debian
    commands:
      - hadolint Dockerfile
      - hadolint Dockerfile.mono
    when:
      branch:
        - master
      event:
        - push
        - pull_request

  - name: docker-dotnet31
    pull: always
    image: plugins/docker:18
    settings:
      build_args:
        - DOTNET_VERSION=3.1-alpine3.16
        - SONAR_SCANNER_VERSION=5.8.0
      cache_from: zzdats/dotnet-sonarscanner
      repo: zzdats/dotnet-sonarscanner
      tag:
        - 3.1
        - 3.1-5.8.0
    environment:
      DOCKER_PASSWORD:
        from_secret: docker_password
      DOCKER_USERNAME:
        from_secret: docker_username
    depends_on:
      - lint
    when:
      branch:
        - master
      event:
        - push

  - name: docker-dotnet6
    pull: always
    image: plugins/docker:18
    settings:
      build_args:
        - DOTNET_VERSION=6.0-alpine3.16
        - SONAR_SCANNER_VERSION=5.8.0
      cache_from: zzdats/dotnet-sonarscanner
      repo: zzdats/dotnet-sonarscanner
      tag:
        - "6.0"
        - 6.0-5.8.0
    environment:
      DOCKER_PASSWORD:
        from_secret: docker_password
      DOCKER_USERNAME:
        from_secret: docker_username
    depends_on:
      - lint
    when:
      branch:
        - master
      event:
        - push

  - name: docker-dotnet7
    pull: always
    image: plugins/docker:18
    settings:
      build_args:
        - DOTNET_VERSION=7.0-alpine3.16
        - SONAR_SCANNER_VERSION=5.8.0
      cache_from: zzdats/dotnet-sonarscanner
      repo: zzdats/dotnet-sonarscanner
      tag:
        - latest
        - "7.0"
        - 7.0-5.8.0
    environment:
      DOCKER_PASSWORD:
        from_secret: docker_password
      DOCKER_USERNAME:
        from_secret: docker_username
    depends_on:
      - lint
    when:
      branch:
        - master
      event:
        - push

  - name: docker-dotnet31-mono
    pull: always
    image: plugins/docker:18
    settings:
      build_args:
        - DOTNET_VERSION=3.1-alpine3.16
        - SONAR_SCANNER_VERSION=5.8.0
      cache_from: zzdats/dotnet-sonarscanner
      dockerfile: Dockerfile.mono
      repo: zzdats/dotnet-sonarscanner
      tag:
        - 3.1-mono
        - 3.1-5.8.0-mono
    environment:
      DOCKER_PASSWORD:
        from_secret: docker_password
      DOCKER_USERNAME:
        from_secret: docker_username
    depends_on:
      - lint
    when:
      branch:
        - master
      event:
        - push

  - name: docker-dotnet6-mono
    pull: always
    image: plugins/docker:18
    settings:
      build_args:
        - DOTNET_VERSION=6.0-alpine3.16
        - SONAR_SCANNER_VERSION=5.8.0
      cache_from: zzdats/dotnet-sonarscanner
      dockerfile: Dockerfile.mono
      repo: zzdats/dotnet-sonarscanner
      tag:
        - 6.0-mono
        - 6.0-5.8.0-mono
    environment:
      DOCKER_PASSWORD:
        from_secret: docker_password
      DOCKER_USERNAME:
        from_secret: docker_username
    depends_on:
      - lint
    when:
      branch:
        - master
      event:
        - push

  - name: docker-dotnet7-mono
    pull: always
    image: plugins/docker:18
    settings:
      build_args:
        - DOTNET_VERSION=7.0-alpine3.16
        - SONAR_SCANNER_VERSION=5.8.0
      cache_from: zzdats/dotnet-sonarscanner
      dockerfile: Dockerfile.mono
      repo: zzdats/dotnet-sonarscanner
      tag:
        - latest-mono
        - 7.0-mono
        - 7.0-5.8.0-mono
    environment:
      DOCKER_PASSWORD:
        from_secret: docker_password
      DOCKER_USERNAME:
        from_secret: docker_username
    depends_on:
      - lint
    when:
      branch:
        - master
      event:
        - push
