ARG DOTNET_VERSION
FROM mcr.microsoft.com/dotnet/sdk:${DOTNET_VERSION}

ARG SONAR_SCANNER_VERSION

ENV PATH="${PATH}:/root/.dotnet/tools"

RUN apt-get update && apt-get install -y --no-install-recommends 'openjdk-11-jre-headless=11.*' 'openjdk-11-jdk-headless=11.*' \
    && dotnet tool install --global dotnet-sonarscanner --version ${SONAR_SCANNER_VERSION} \
    && rm -rf /var/lib/apt/lists/*
