name: Docker Image CI

on:
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Lint
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile

  build:
    strategy:
      matrix:
        version: [ "6.0", "8.0" ]
        sq_version: [ "8.0.3" ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build Alpine
        uses: docker/build-push-action@v6
        with:
          push: false
          build-args: |
            DOTNET_VERSION=${{ matrix.version }}-alpine3.20
            SONAR_SCANNER_VERSION=${{ matrix.sq_version }}
          tags: |
            zzdats/dotnet-sonarscanner:${{ matrix.version }}
            zzdats/dotnet-sonarscanner:${{ matrix.version }}-${{ matrix.sq_version }}
      - name: Build Ubuntu
        uses: docker/build-push-action@v6
        with:
          push: false
          file: Dockerfile.ubuntu
          build-args: |
            DOTNET_VERSION=${{ matrix.version }}-jammy
            SONAR_SCANNER_VERSION=${{ matrix.sq_version }}
          tags: |
            zzdats/dotnet-sonarscanner:${{ matrix.version }}-ubuntu
            zzdats/dotnet-sonarscanner:${{ matrix.version }}-${{ matrix.sq_version }}-ubuntu
